# Generated by Django 4.2.2 on 2023-07-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='user',
            new_name='author',
        ),
    ]
