# Generated by Django 4.2.2 on 2023-07-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='author',
            new_name='user',
        ),
    ]
