# Generated by Django 4.2.2 on 2023-07-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_rename_author_course_user_rename_author_lesson_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=5000, verbose_name='стоимость курса'),
        ),
    ]
