# Generated by Django 4.2.2 on 2023-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=5000, verbose_name='стоимость курса'),
        ),
    ]
