# Generated by Django 4.2.2 on 2023-07-22 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_app.payments', verbose_name='платеж'),
            preserve_default=False,
        ),
    ]
