# Generated by Django 4.2.2 on 2023-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_subscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID намерения платежа'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID метода платежа'),
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cтатус платежа'),
        ),
    ]
