# Generated by Django 4.2.2 on 2023-07-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0011_payments_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID намерения платежа'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID метода платежа'),
        ),
    ]
