# Generated by Django 4.2.2 on 2023-07-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_alter_payments_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус подписки'),
        ),
    ]
