# Generated by Django 4.2.2 on 2023-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0013_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время обновления'),
        ),
    ]
